### ISSUE TITLE
Error in sea() from quantile.default with NaNs

### ISSUE THREAD

**Issue by csavoldelli** [OpenDendro/dplR#12]
Hi Andy,

This is my first issue report on GitHub so apologies if I do things wrong! 

I have a small sample (43 series) that cover ~150 years, but the majority of the sample depth starts in the last 100. I'm attempting to run the sea() function to evaluate ~5 storm event years. The code worked some days ago, but now I get the error below. Unfortunately I'm quite new to R and even looking at the function's code I couldn't tell where setting na.rm to TRUE might help, or if there is something wrong with my data.

> grow.sea <- sea(grow.rwi, event.years, lag = 5, resample = 1000)
Error in quantile.default(newX[, i], ...) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

The preceding and following code is nearly identical to the example given [here](https://rdrr.io/cran/dplR/man/sea.html), but happy to provide further context. Thank you either way for this great package!

Carolyn

**Comment by AndyBunn** [comment]
Hi Carolyn. Probably best if you email me the file and the R script you are using unless you can produce a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the error. Happy to look into it.

**Comment by csavoldelli** [comment]
Hi Andy - thank you so much for your offer! Very simple error on my part, apologies for taking your time. I was running the function on an rwi rather than a detrended chronology. Works well with the latter.

**Comment by AndyBunn** [comment]
No worries!

From: csavoldelli ***@***.***>
Date: Monday, May 2, 2022 at 3:17 PM
To: AndyBunn/dplR ***@***.***>
Cc: Andy Bunn ***@***.***>, Comment ***@***.***>
Subject: Re: [AndyBunn/dplR] Error in sea() from quantile.default with NaNs (Issue #12)

Hi Andy - thank you so much for your offer! Very simple error on my part, apologies for taking your time. I was running the function on an rwi rather than a detrended chronology. Works well with the latter.
